# Generated by Django 3.2.19 on 2023-05-04 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
            ],
        ),
    ]
